### ISSUE TITLE
how is the  Tabbed Inline Admin used

### ISSUE THREAD

**Issue by acmeguy** [hypy13/django-daisy#10]
I find no documentation or examples covering that.

Thank you for a great UI.

**Comment by hypy13** [comment]
Thanks,

You’re right—docs were missing, but I’ve added them to the README.

To use Tabbed Inline Admin, extend your TabularInline (or StackedInline) with NavTabMixin like this:

```
class ChoiceInline(admin.TabularInline, NavTabMixin):
    model = Choice
    extra = 1

```
