### ISSUE TITLE
I got error " 'Settings' object has no attribute 'APPS_REORDER' "

### ISSUE THREAD

**Issue by yaserantariksa** [hypy13/django-daisy#2]
I try this package, and i just make default django project and django app. its work when display admin login page, but when login i got error " 'Settings' object has no attribute 'APPS_REORDER' " and can not enter dashboard page. 

is there any clue how to solve this? thanks.

**Comment by yaserantariksa** [comment]
just add APPS_REORDER = {} and its works

**Comment by hypy13** [comment]
hi there,

thanks for report, i will fix it
also im working on tox testing to test the app before every release

:+1:
