### ISSUE TITLE
Filtering and Searching does not work because of JS

### ISSUE THREAD

**Issue by MrBoMin** [hypy13/django-daisy#3]
Is there any solution for working with Javascript for filtering and searching? These features does not work for me.

**Comment by hypy13** [comment]
hi @MrBoMin 

you mean using ajax to search or filter data?

**Comment by MrBoMin** [comment]
yes brother! It was okay, It is because of my browser's cache. It works

**Comment by hypy13** [comment]
Cool, 
thanks for updating me ;)
