### ISSUE TITLE
Custom CSS for Own styles

### ISSUE THREAD

**Issue by JaredBRSK** [hypy13/django-daisy#4]
Just want to see if its possible to easily override or add a new Style, Id like to create a custom defaults style along with the other styels

**Comment by hypy13** [comment]
Hi there
Actually its currently not implemented 
But i will definitely work on it.

But for now
You can override base.html and add you styles
In your root project directory, create templates/admin/base.html
------

Or simple fork project and have full control over it
❤️❤️

**Comment by hypy13** [comment]
@JaredBRSK 

hey there again

now you can add your custom styles by defining them in settings.py
like following
```
DAISY_SETTINGS = {
    'EXTRA_STYLES': [],  # List of extra stylesheets to be loaded in base.html (optional)
    'EXTRA_SCRIPTS': [],  # List of extra script URLs to be loaded in base.html (optional)
    }

```

please update the installation and check out [Readme](https://github.com/hypy13/django-daisy?tab=readme-ov-file#project-customizations)
