### ISSUE TITLE
 You don’t have permission to view or edit anything.

### ISSUE THREAD

**Issue by birddevelper** [hypy13/django-daisy#7]
Hi, 
Thank you for the great package.
I get the following message after adding the app to existing project:
![image](https://github.com/user-attachments/assets/c53ff64a-01f5-44dd-9d83-252bd529efcd)

**Comment by hypy13** [comment]
Hi. Tnx

I think there should be problem with the configuration 
Did u exactly follow the configuration process in readme?

And please provide more details so i can help you:)

**Comment by birddevelper** [comment]
Yes, I installed the package, added the app to installed_app list, and added config parameter in one apps app.py file.

**Comment by hypy13** [comment]
django_daisy should place above default django.contrib.admin

Is it?

**Comment by birddevelper** [comment]
No it wasn't.
I moved it above the `django.contrib.admin` and solved the issue.✅
Thanks

**Comment by hypy13** [comment]
always :)
