### ISSUE TITLE
List UI issues

### ISSUE THREAD

**Issue by birddevelper** [hypy13/django-daisy#8]
There are some issue in the UI:

- The `search_help_text` is miss placed
- The filter button doesn't work

![image](https://github.com/user-attachments/assets/b7adba43-8438-4022-8e89-8d0ef400fea1)

**Comment by hypy13** [comment]
Thank you for reporting these issues and for using this theme! 

    The search_help_text issue has been fixed by adding a tooltip that appears when you hover over the search input field.
    Regarding the filter button, it seems your admin class hasn’t set list_filter. 
To improve the UI, I’ve made sure the filter button is hidden when no filters are available.

Let me know if you encounter any other issues or need further assistance. Thanks again for your feedback!

try updtaing the package and clear ur browser cache 
cheers
