### ISSUE TITLE
UI Overflow Issue: "View on Site" Button

### ISSUE THREAD

**Issue by rynBenAmor** [hypy13/django-daisy#9]
I’ve encountered a minor UI overflow issue related to the Django admin interface. While I couldn’t reproduce this on your demo site, it appears when using the typical Django models conventions. specifically if a model includes a get_absolute_url method, the admin interface displays a "View on Site" button next to the "History" button.

It seems your panel theme package does not account for this button, causing it to overflow on the x-axis.

ty so much for your continued efforts and the wonderful updates to this project
![2](https://github.com/user-attachments/assets/abe4bdfb-ddab-466c-b8da-3baca3c49371)
![1](https://github.com/user-attachments/assets/b2202c16-1c97-4c15-bc28-5c7af13a55a0)

**Comment by hypy13** [comment]
Thank you for your detailed report!
The responsive bug has been fixed. You can update the project, and I would be humbled to hear about any other issues or feedback you may have.
